using System.Net.Security;
using Business.Data;
using Business.Factories;
using Microsoft.Extensions.Configuration;

namespace Business.Tests
{
    public class DataStorageFactoryTests
    {
        // Generated by chatGPT

        // First test is only generated by chatGPT
        // First it sets up a in memory configuration with the DataStorageType set to Json
        // Then it creates a IConfiguration instance
        // Then it gets the DataStorageType from the configuration
        // Assert.notnull is used to ensure that the storageType is not null
        // Then it creates a new DataStorageFactory to get the storage type
        //  Then it callas the method
        // then verify that the storage instance i JsonStorage

        [Fact]
        public void CreateDataStorage_ReturnsJsonStorage_WhenConfiguredAsJson()
        {
            // Arrange
            var inMemorySettings = new Dictionary<string, string>
            {
                { "DataStorageType", "Json" }
            };

            IConfiguration configuration = new ConfigurationBuilder()
                .AddInMemoryCollection(inMemorySettings as IEnumerable<KeyValuePair<string, string?>>)
                .Build();

            var storageType = configuration["DataStorageType"];
            Assert.NotNull(storageType); 
            var factory = new DataStorageFactory(storageType!);


            // Act
            var dataStorage = factory.CreateDataStorage();

            // Assert
            Assert.IsType<JsonStorage>(dataStorage);
        }

        [Fact]
        public void CreateDataStorage_ThrowsException_WhenInvalidTypeConfigured()
        {
            // Arrange
            var inMemorySettings = new Dictionary<string, string>
            {
                { "DataStorageType", "InvalidType" }
            };

            IConfiguration configuration = new ConfigurationBuilder()
                .AddInMemoryCollection(inMemorySettings as IEnumerable<KeyValuePair<string, string?>>)
                .Build();

            var storageType = configuration["DataStorageType"];
            Assert.NotNull(storageType);
            var factory = new DataStorageFactory(storageType!);

            // Act & Assert
            Assert.Throws<InvalidOperationException>(() => factory.CreateDataStorage());
        }

        [Fact]
        public void CreateDataStorage_WithNullStorageType_ThrowsException()
        {
            var factory = new DataStorageFactory(null!);
            Assert.Throws<InvalidOperationException>(() => factory.CreateDataStorage());
        }

    }
}
